### ISSUE TITLE
Graph algorithms unavailable for neo4j 4.0

### ISSUE THREAD

**Issue by scarltee** [MannLabs/CKG#22]
Hi,

I am trying to install CKG on a macbook machine. It seems that currently one can only download neo4j 4.0 or 3.5.18+, where graph algorithms seem to be unavailable. 

When I try to build from terminal with `python builder.py -b full -u neo4j`, it returns:
Traceback (most recent call last):
  File "builder.py", line 14, in <module>
    from graphdb_builder.builder import importer, loader
ModuleNotFoundError: No module named 'graphdb_builder'

Is there a way around it? Thanks!

**Comment by albsantosdel** [comment]
Hi, 
There are two issues:
1) Neo4j version. The current Neo4j release is 4.0.5 and as you mention, the graph algorithm plugin is still not available. However, if you install the Neo4j Desktop application (https://neo4j.com/download/neo4j-desktop/?edition=desktop&flavour=osx&release=1.2.9&offline=true) when you create a local graph, it will let you choose the version of Neo4j that you want to use (CKG uses 3.5.14).
2) ModuleNotFoundError. It seems that your PYTHONPATH has not been updated. I recommend you to follow the instructions here: https://ckg.readthedocs.io/en/latest/intro/getting-started-with-build.html#add-ckg-to-bashrc

**Comment by scarltee** [comment]
Thanks! Issues solved.

**Comment by sitashmarajbhandari7879** [comment]
Hello, when I try to build Neo4j Graph database in windows I keep getting this error

![1 1](https://user-images.githubusercontent.com/25837077/104835060-3f9bfb80-58a4-11eb-92ac-fd4222849aee.PNG)


(CKG_ENV) C:\Users\sitas\CKG\src\graphdb_builder\builder>python builder.py -b full -u neo4j


Traceback (most recent call last):
  File "builder.py", line 14, in <module>
    from graphdb_builder.builder import importer, loader
  File "C:\Users\sitas\CKG\src\graphdb_builder\builder\importer.py", line 20, in <module>
    from graphdb_builder.users import users_controller as uh
  File "C:\Users\sitas\CKG\src\graphdb_builder\users\users_controller.py", line 8, in <module>
    from passlib.hash import bcrypt
  File "C:\Users\sitas\CKG_ENV\lib\site-packages\passlib\hash.py", line 25, in <module>
    from passlib.registry import _proxy
  File "C:\Users\sitas\CKG_ENV\lib\site-packages\passlib\registry.py", line 12, in <module>
    from passlib.ifc import PasswordHash
  File "C:\Users\sitas\CKG_ENV\lib\site-packages\passlib\ifc.py", line 10, in <module>
    from passlib.utils.decor import deprecated_method
  File "C:\Users\sitas\CKG_ENV\lib\site-packages\passlib\utils\_init_.py", line 845, in <module>
    from time import clock as timer
ImportError: cannot import name 'clock' from 'time' (unknown location)


can anyone please help me? I am new to neo4j and CKG
