### ISSUE TITLE
Isuue with building ckg in Neo4j

### ISSUE THREAD

**Issue by sitashmarajbhandari7879** [MannLabs/CKG#48]
Hello, when I try to build Neo4j Graph database in windows I keep getting this error

![1 1](https://user-images.githubusercontent.com/25837077/104835060-3f9bfb80-58a4-11eb-92ac-fd4222849aee.PNG)

(CKG_ENV) C:\Users\sitas\CKG\src\graphdb_builder\builder>python builder.py -b full -u neo4j

Traceback (most recent call last):
  File "builder.py", line 14, in <module>
    from graphdb_builder.builder import importer, loader
  File "C:\Users\sitas\CKG\src\graphdb_builder\builder\importer.py", line 20, in <module>
    from graphdb_builder.users import users_controller as uh
  File "C:\Users\sitas\CKG\src\graphdb_builder\users\users_controller.py", line 8, in <module>
    from passlib.hash import bcrypt
  File "C:\Users\sitas\CKG_ENV\lib\site-packages\passlib\hash.py", line 25, in <module>
    from passlib.registry import _proxy
  File "C:\Users\sitas\CKG_ENV\lib\site-packages\passlib\registry.py", line 12, in <module>
    from passlib.ifc import PasswordHash
  File "C:\Users\sitas\CKG_ENV\lib\site-packages\passlib\ifc.py", line 10, in <module>
    from passlib.utils.decor import deprecated_method
  File "C:\Users\sitas\CKG_ENV\lib\site-packages\passlib\utils\_init_.py", line 845, in <module>
    from time import clock as timer
ImportError: cannot import name 'clock' from 'time' (unknown location)

can anyone please help me? I am new to neo4j and CKG

**Comment by albsantosdel** [comment]
Hi @sitashmarajbhandari7879 
This is not related to Neo4j but instead a python error.
What version of python are you using? Based on the error it could be that you are using Python3.8 and CKG requires Python3.7. 
Let me know if that is not the case.

Thank you.
