### ISSUE TITLE
CKG Docker Container

### ISSUE THREAD

**Issue by XiangZhengCPR** [MannLabs/CKG#72]
Hi Alberto,

I was trying to install CKG Docker Container (https://ckg.readthedocs.io/en/latest/intro/getting-started-with-docker.html):
 
I finished following steps:
  
![image](https://user-images.githubusercontent.com/98458828/154981334-59019cb5-c109-441a-9959-cc959bdbec2c.png)
![image](https://user-images.githubusercontent.com/98458828/154981372-285e577c-3100-4c71-934a-dab56258812f.png)

However, I was stuck with “access CKG app: http://localhost:8050/”. It showed me “Internal Server Error”.

![image](https://user-images.githubusercontent.com/98458828/154981407-73d8bdaa-7c48-4fa4-87b8-7ea472f2d3fe.png)

 
![image](https://user-images.githubusercontent.com/98458828/154981432-e50173cd-70e2-43d0-8ff1-80679092a8dd.png)

Could you please help me out with this issue? Thank you very much.

Best regards,
Xiang

**Comment by caoool** [comment]
+1

**Comment by anijudy** [comment]
Same here.

I'm using a Linux server, with docker 19.03.8 installed.

I was able to build the image successfully, and had no problem accessing neo4j or Jupyter Hub, but had no luck with CKG app.
![image](https://user-images.githubusercontent.com/10775353/155447862-b6bf52db-bdfa-4d75-a543-db91e79ab555.png)

![image](https://user-images.githubusercontent.com/10775353/155447720-8597ce32-dc30-4d2e-84f4-4a661e2c580f.png)

![image](https://user-images.githubusercontent.com/10775353/155447778-d37db692-6683-4b68-a8a9-0305f0078748.png)

I went into the docker, but did not find any log inside the directory /CKG/log.
![image](https://user-images.githubusercontent.com/10775353/155448285-59136fad-57e9-45d8-8e98-5b7483cde7df.png)

Any help would be appreciated!

Best,
Yifan

**Comment by caoool** [comment]
Some more logs from docker logs during startup.

```
[W 2022-02-24 09:12:17.368 JupyterHub proxy:688] Running JupyterHub without SSL.  I hope there is SSL termination happening somewhere else...
[I 2022-02-24 09:12:17.368 JupyterHub proxy:691] Starting proxy @ http://:8090/
Usage: celery [OPTIONS] COMMAND [ARGS]...

Error: Invalid value for '-A' / '--app':
Unable to load celery application.
While trying to load the module ckg.report_manager.worker the following error occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/celery/app/utils.py", line 384, in find_app
    sym = symbol_by_name(app, imp=imp)
  File "/usr/local/lib/python3.7/site-packages/kombu/utils/imports.py", line 61, in symbol_by_name
    return getattr(module, cls_name) if cls_name else module
AttributeError: module 'ckg.report_manager' has no attribute 'worker'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/celery/bin/celery.py", line 53, in convert
    return find_app(value)
  File "/usr/local/lib/python3.7/site-packages/celery/app/utils.py", line 387, in find_app
    sym = imp(app)
  File "/usr/local/lib/python3.7/site-packages/celery/utils/imports.py", line 100, in import_from_cwd
    return imp(module, package=package)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/CKG/ckg/report_manager/worker.py", line 3, in <module>
    from ckg.report_manager.apps import projectCreation, dataUpload
  File "/CKG/ckg/report_manager/apps/dataUpload.py", line 10, in <module>
    from ckg.analytics_core.viz import viz
  File "/CKG/ckg/analytics_core/viz/viz.py", line 6, in <module>
    import dash_core_components as dcc
  File "/usr/local/lib/python3.7/site-packages/dash_core_components/__init__.py", line 8, in <module>
    import dash as _dash
  File "/usr/local/lib/python3.7/site-packages/dash/__init__.py", line 1, in <module>
    from .dash import Dash, no_update  # noqa: F401
  File "/usr/local/lib/python3.7/site-packages/dash/dash.py", line 19, in <module>
    import flask
  File "/usr/local/lib/python3.7/site-packages/flask/__init__.py", line 21, in <module>
    from .app import Flask, Request, Response
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 26, in <module>
    from . import cli, json
  File "/usr/local/lib/python3.7/site-packages/flask/json/__init__.py", line 21, in <module>
    from itsdangerous import json as _json
ImportError: cannot import name 'json' from 'itsdangerous' (/usr/local/lib/python3.7/site-packages/itsdangerous/__init__.py)

Usage: celery [OPTIONS] COMMAND [ARGS]...

Error: Invalid value for '-A' / '--app':
Unable to load celery application.
While trying to load the module ckg.report_manager.worker the following error occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/celery/app/utils.py", line 384, in find_app
    sym = symbol_by_name(app, imp=imp)
  File "/usr/local/lib/python3.7/site-packages/kombu/utils/imports.py", line 61, in symbol_by_name
    return getattr(module, cls_name) if cls_name else module
AttributeError: module 'ckg.report_manager' has no attribute 'worker'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/celery/bin/celery.py", line 53, in convert
    return find_app(value)
  File "/usr/local/lib/python3.7/site-packages/celery/app/utils.py", line 387, in find_app
    sym = imp(app)
  File "/usr/local/lib/python3.7/site-packages/celery/utils/imports.py", line 100, in import_from_cwd
    return imp(module, package=package)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/CKG/ckg/report_manager/worker.py", line 3, in <module>
    from ckg.report_manager.apps import projectCreation, dataUpload
  File "/CKG/ckg/report_manager/apps/dataUpload.py", line 10, in <module>
    from ckg.analytics_core.viz import viz
  File "/CKG/ckg/analytics_core/viz/viz.py", line 6, in <module>
    import dash_core_components as dcc
  File "/usr/local/lib/python3.7/site-packages/dash_core_components/__init__.py", line 8, in <module>
    import dash as _dash
  File "/usr/local/lib/python3.7/site-packages/dash/__init__.py", line 1, in <module>
    from .dash import Dash, no_update  # noqa: F401
  File "/usr/local/lib/python3.7/site-packages/dash/dash.py", line 19, in <module>
    import flask
  File "/usr/local/lib/python3.7/site-packages/flask/__init__.py", line 21, in <module>
    from .app import Flask, Request, Response
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 26, in <module>
    from . import cli, json
  File "/usr/local/lib/python3.7/site-packages/flask/json/__init__.py", line 21, in <module>
    from itsdangerous import json as _json
ImportError: cannot import name 'json' from 'itsdangerous' (/usr/local/lib/python3.7/site-packages/itsdangerous/__init__.py)

Usage: celery [OPTIONS] COMMAND [ARGS]...

Error: Invalid value for '-A' / '--app':
Unable to load celery application.
While trying to load the module ckg.report_manager.worker the following error occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/celery/app/utils.py", line 384, in find_app
    sym = symbol_by_name(app, imp=imp)
  File "/usr/local/lib/python3.7/site-packages/kombu/utils/imports.py", line 61, in symbol_by_name
    return getattr(module, cls_name) if cls_name else module
AttributeError: module 'ckg.report_manager' has no attribute 'worker'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/celery/bin/celery.py", line 53, in convert
    return find_app(value)
  File "/usr/local/lib/python3.7/site-packages/celery/app/utils.py", line 387, in find_app
    sym = imp(app)
  File "/usr/local/lib/python3.7/site-packages/celery/utils/imports.py", line 100, in import_from_cwd
    return imp(module, package=package)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/CKG/ckg/report_manager/worker.py", line 3, in <module>
    from ckg.report_manager.apps import projectCreation, dataUpload
  File "/CKG/ckg/report_manager/apps/dataUpload.py", line 10, in <module>
    from ckg.analytics_core.viz import viz
  File "/CKG/ckg/analytics_core/viz/viz.py", line 6, in <module>
    import dash_core_components as dcc
  File "/usr/local/lib/python3.7/site-packages/dash_core_components/__init__.py", line 8, in <module>
    import dash as _dash
  File "/usr/local/lib/python3.7/site-packages/dash/__init__.py", line 1, in <module>
    from .dash import Dash, no_update  # noqa: F401
  File "/usr/local/lib/python3.7/site-packages/dash/dash.py", line 19, in <module>
    import flask
  File "/usr/local/lib/python3.7/site-packages/flask/__init__.py", line 21, in <module>
    from .app import Flask, Request, Response
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 26, in <module>
    from . import cli, json
  File "/usr/local/lib/python3.7/site-packages/flask/json/__init__.py", line 21, in <module>
    from itsdangerous import json as _json
ImportError: cannot import name 'json' from 'itsdangerous' (/usr/local/lib/python3.7/site-packages/itsdangerous/__init__.py)

09:12:17.964 [ConfigProxy] info: Proxying http://*:8090 to (no default)
```

**Comment by caoool** [comment]
Yo guys, I think I have managed to solve it.
It appears that the issues is related with broken dependencies.
1. itsdangerous
2. reportlab
In order to run ckgapp, I have downgraded them
1. itsdnagerous 2.0.1
2. reportlab 3.6.6

In the project's root directory, navigate to requirements.txt, add below two lines
```
itsdangerous==2.0.1
reportlab==3.6.6
```

rebuild the docker image, I was able to get ckgapp running.
Let me know how it goes.

**Comment by anijudy** [comment]
Hi @caoool !

It works like a charm! Thank you so much!

BTW, would you mind sharing the path where I can find the docker log?

Best,
Yifan

**Comment by caoool** [comment]
Ya it's just 'docker logs ckgapp -f'

**Comment by albsantosdel** [comment]
@caoool Thank you! 
Currently testing if an upgraded version of Flask solves the issue without causing problems and pinning the reportlab version

**Comment by ezy1999** [comment]
It doesn't work ,still the same problem with the modified requirements.

**Comment by Meadunce** [comment]
@XiangZhengCPR  您好，请问这个问题解决了吗？
